// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3VQUry0Mvhzh3CpMhzxOCi43Z78ycw8',
    appId: '1:608225598021:web:b5b2125014dbc6747b212c',
    messagingSenderId: '608225598021',
    projectId: 'portfolio-8cf77',
    authDomain: 'portfolio-8cf77.firebaseapp.com',
    storageBucket: 'portfolio-8cf77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6wpUyVn-fUWaZPYnoXAlsc-WwOHq6So',
    appId: '1:608225598021:android:e085f2650513c9b87b212c',
    messagingSenderId: '608225598021',
    projectId: 'portfolio-8cf77',
    storageBucket: 'portfolio-8cf77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHJZ6gVFXCHc1srB0nCtMHUO76HrFVbI',
    appId: '1:608225598021:ios:2f2e8cb9611c14447b212c',
    messagingSenderId: '608225598021',
    projectId: 'portfolio-8cf77',
    storageBucket: 'portfolio-8cf77.firebasestorage.app',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
